CREATE DATABASE IF NOT EXISTS Subs;

USE Subs;

CREATE TABLE Movie(
Movie_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Movie_ID),
Name VARCHAR(32)
) ENGINE = INNODB;

CREATE TABLE Sub(
ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(ID),
Movie_ID INT NOT NULL,
FOREIGN KEY(Movie_ID) REFERENCES Movie(Movie_ID),
Sub_ID INT NOT NULL,
FromTime VARCHAR(11) NOT NULL,
ToTime VARCHAR(11) NOT NULL
) ENGINE = INNODB;

CREATE TABLE SubText(
SubText_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(SubText_ID),
Sub_ID INT NOT NULl,
FOREIGN KEY(Sub_ID) REFERENCES Sub(ID),
Line VARCHAR(100)
) ENGINE = INNODB;