//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.08 at 03:05:44 PM CEST 
//


package trivia;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrivPost" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="triviaText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fromTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                   &lt;element name="toTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trivPost"
})
@XmlRootElement(name = "trivia")
public class Trivia {

    @XmlElement(name = "TrivPost")
    protected List<Trivia.TrivPost> trivPost;

    /**
     * Gets the value of the trivPost property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trivPost property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrivPost().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Trivia.TrivPost }
     * 
     * 
     */
    public List<Trivia.TrivPost> getTrivPost() {
        if (trivPost == null) {
            trivPost = new ArrayList<Trivia.TrivPost>();
        }
        return this.trivPost;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="triviaText" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fromTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *         &lt;element name="toTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "triviaText",
        "fromTime",
        "toTime"
    })
    public static class TrivPost {

        @XmlElement(required = true)
        protected String triviaText;
        @XmlElement(required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar fromTime;
        @XmlElement(required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar toTime;
        @XmlAttribute(name = "id")
        protected Byte id;

        /**
         * Gets the value of the triviaText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTriviaText() {
            return triviaText;
        }

        /**
         * Sets the value of the triviaText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTriviaText(String value) {
            this.triviaText = value;
        }

        /**
         * Gets the value of the fromTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFromTime() {
            return fromTime;
        }

        /**
         * Sets the value of the fromTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFromTime(XMLGregorianCalendar value) {
            this.fromTime = value;
        }

        /**
         * Gets the value of the toTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getToTime() {
            return toTime;
        }

        /**
         * Sets the value of the toTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setToTime(XMLGregorianCalendar value) {
            this.toTime = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setId(Byte value) {
            this.id = value;
        }

    }

}
